#!/bin/sh

repo="https://github.com/DOMjudge/domjudge.git"

if [ -n "$1" ]; then
	repo=$1
fi

if [ ! -d domjudge.git ]; then
	git clone --bare $repo
fi

cd domjudge.git
git fetch $repo

# this resets the date of FETCH_HEAD for further caching
lastcommitdate=`git show -s --format=%ct HEAD`
touch -d@$lastcommitdate FETCH_HEAD

cd ..
tar cf domjudge.git.tar domjudge.git
# this resets the date of the tgz file
touch -d@$lastcommitdate domjudge.git.tar

docker="/usr/bin/docker"
if [ -x "/usr/bin/docker.io" ]; then
	# debian/Ubuntu uses docker.io instead of docker
	docker="/usr/bin/docker.io"
fi
$docker build -t domjudge .
